name: WorldGenPlugin
version: '${project.version}'
main: me.butter.worldgenplugin.WorldGenPlugin
commands:
  generate:
    description: Your description
  giverole:
    description: Your description
  pf:
    description: Your description